### ISSUE TITLE
the "stable-2.13" version throws exception

### ISSUE THREAD

**Issue by gshiva** [GerritCodeReview/plugins_reviewers-by-blame#1]
When installed with gerrit 2.13, the jar from 

https://gerrit-ci.gerritforge.com/job/plugin-reviewers-by-blame-stable-2.13/

https://gerrit-ci.gerritforge.com/job/plugin-reviewers-by-blame-stable-2.13/lastSuccessfulBuild/artifact/buck-out/gen/plugins/reviewers-by-blame/reviewers-by-blame.jar

Following exception occurs on every push:
Caused by: java.lang.NoSuchFieldError: change
        at com.googlesource.gerrit.plugins.reviewersbyblame.ChangeUpdatedListene
r.onEvent(ChangeUpdatedListener.java:87)

**Comment by lucamilanesio** [comment]
@gshiva this is purely a mirror of the Gerrit code review projects, hosted on gerrit-review.googlesource.com. Can you please post your issue to the mailing list at https://groups.google.com/forum/#!forum/repo-discuss?
